### ISSUE TITLE
Can not execute model.train() - error: "The system cannot find the file specified"

### ISSUE THREAD

**Issue by habibatabay** [salesforce/Merlion#75]
**Describe the bug**
Hi,
I just installed Merlion in my new anaconda environment on windows 10.
The installation was fine except the build error of prophet package using wheel which was solved by installing "libpython m2w64-toolchain -c msys2".
But when I tried to execute the sample code of anomaly detection it throws an error: "FileNotFoundError: [WinError 2] The system cannot find the file specified".

**Expected behavior**
The console output is:

>>> model.train(train_data=train_data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\merlion\lib\site-packages\merlion\models\defaults.py", line 88, in train        
    ModelFactory.create(
  File "C:\Anaconda3\envs\merlion\lib\site-packages\merlion\models\factory.py", line 89, in create
    model._load_state(kwargs)
  File "C:\Anaconda3\envs\merlion\lib\site-packages\merlion\models\base.py", line 367, in _load_state     
    self.__setstate__(state_dict)
  File "C:\Anaconda3\envs\merlion\lib\site-packages\merlion\models\anomaly\random_cut_forest.py", line 138, in __setstate__
    RCFSerDe = JVMSingleton.gateway().jvm.com.amazon.randomcutforest.serialize.RandomCutForestSerDe       
  File "C:\Anaconda3\envs\merlion\lib\site-packages\merlion\models\anomaly\random_cut_forest.py", line 40, in gateway
    cls._gateway = JavaGateway.launch_gateway(classpath=classpath, javaopts=javaopts)
  File "C:\Anaconda3\envs\merlion\lib\site-packages\py4j\java_gateway.py", line 2159, in launch_gateway   
    _ret = launch_gateway(
  File "C:\Anaconda3\envs\merlion\lib\site-packages\py4j\java_gateway.py", line 331, in launch_gateway    
    proc = Popen(
  File "C:\Anaconda3\envs\merlion\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Anaconda3\envs\merlion\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

What can I do to solve this problem?
Thanks

**Comment by aadyotb** [comment]
It sounds like you need to install Java.

**Comment by habibatabay** [comment]
Thanks for your comment.
I installed  Java SE Runtime Environment 10.
The problem is solved.
Thank you.
