### ISSUE TITLE
[BUG] ValueError: invalid literal for int() with base 10: b''

### ISSUE THREAD

**Issue by pnsafari** [salesforce/Merlion#91]
**Describe the bug**
While trying to run the example of anomaly detection as presented in the README file, I got this ValueError. The full traceback of the error is presented below. 

**To Reproduce**
Just try to run the example of Anomaly detection as presented in the README file. 

**Expected behavior**
Run with the expected outputs as the anomaly detection example in the README file.

**Screenshots**
```
Traceback (most recent call last):
  File "/home/anomaly.py", line 54, in <module>
    model.train(train_data=train_data)
  File "/home/anaconda3/envs/timeseries/lib/python3.7/site-packages/merlion/models/defaults.py", line 94, in train
    max_n_samples=512,
  File "/home/anaconda3/envs/timeseries/lib/python3.7/site-packages/merlion/models/factory.py", line 89, in create
    model._load_state(kwargs)
  File "/home/anaconda3/envs/timeseries/lib/python3.7/site-packages/merlion/models/base.py", line 365, in _load_state
    self.__setstate__(state_dict)
  File "/home/anaconda3/envs/timeseries/lib/python3.7/site-packages/merlion/models/anomaly/random_cut_forest.py", line 138, in __setstate__
    RCFSerDe = JVMSingleton.gateway().jvm.com.amazon.randomcutforest.serialize.RandomCutForestSerDe
  File "/home/anaconda3/envs/timeseries/lib/python3.7/site-packages/merlion/models/anomaly/random_cut_forest.py", line 40, in gateway
    cls._gateway = JavaGateway.launch_gateway(classpath=classpath, javaopts=javaopts)
  File "/home/anaconda3/envs/timeseries/lib/python3.7/site-packages/py4j/java_gateway.py", line 2165, in launch_gateway
    use_shell=use_shell)
  File "/home/anaconda3/envs/timeseries/lib/python3.7/site-packages/py4j/java_gateway.py", line 337, in launch_gateway
    _port = int(proc.stdout.readline())
ValueError: invalid literal for int() with base 10: b''
```
**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Merlion Version 1.1.3

**Additional context**
N/A

**Comment by pnsafari** [comment]
@aadyotb thanks, that is the fix.
